apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "demo-project.fullname" . }}
spec:
  hosts:
  - {{ .Values.domain }}
  gateways:
  - {{ include "demo-project.fullname" . }}
  http:
  - name: webapi1
    match:
    - uri:
        exact: /api
    redirect:
      uri: /api/

  - name: webapi2
    match:
    - uri:
        prefix: /api/
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ include "demo-project.fullname" . }}-webapi

  - name: web
    route:
    - destination:
        host: {{ include "demo-project.fullname" . }}-web
