apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: web
          image: web
          ports:
            - containerPort: 5232
          volumeMounts:
            - name: configmap-volume
              mountPath: /app/config
      volumes:
        - name: configmap-volume
          configMap:
            name: webapi
