apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: webapi

commonLabels:
  app: webapi

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: webapi
    files:
      - appsettings.json
