apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-project.fullname" . }}-web
  labels:
    app: web
    {{- include "demo-project.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "WebApiUrl": "http://{{ include "demo-project.fullname" . }}-webapi"
    }
