apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-project.fullname" . }}-web
  labels:
    app: web
    {{- include "demo-project.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      {{- include "demo-project.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: web
        {{- include "demo-project.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.secret }}
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag}}"
          volumeMounts:
          - name: configmap-volume
            mountPath: /app/config
          ports:
          - containerPort: 80
            protocol: TCP
      volumes:
      - name: configmap-volume
        configMap:
          name: {{ include "demo-project.fullname" . }}-web
          