apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-project.fullname" . }}-webapi
  labels:
    app: webapi
    {{- include "demo-project.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "Message": "{{ .Values.message }}"
    }

