apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-project.fullname" . }}-webapi
  labels:
    app: webapi
    {{- include "demo-project.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
      {{- include "demo-project.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: webapi
        {{- include "demo-project.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.secret }}
      containers:
      - name: webapi
        image: "{{ .Values.webapi.image.repository }}:{{ .Values.webapi.image.tag}}"
        volumeMounts:
        - name: configmap-volume
          mountPath: /app/config
        ports:
        - containerPort: 80
          protocol: TCP
      volumes:
      - name: configmap-volume
        configMap:
          name: {{ include "demo-project.fullname" . }}-webapi
          
          