apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-project.fullname" . }}-webapi
  labels:
    app: webapi
    {{- include "demo-project.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: webapi
    {{- include "demo-project.selectorLabels" . | nindent 4 }}
